[custom]
;不要随意改变关键字，否则会导致出错

; 📌📌📌过滤名称节点 正则匹配
exclude_remarks=(群组|Expire|Traffic|Zero Trust|备用登录|备用面板|计划|面板|商业使用|域名|邀请|免翻|本站|用户|公益|捐贈|漏洞|永久虚通路|到期|剩余流量|时间|官网|产品|平台|套餐到期|二手倒卖|重置|剩余|过期|机场|订阅|分享|客服)

add_emoji=true
remove_old_emoji=true
emoji=!!import:https://raw.githubusercontent.com/sun2ot/ClashRules/main/config/emoji_new.list

;设置规则标志位
; 全球直连
ruleset=🌏 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🌏 全球直连,https://raw.githubusercontent.com/Hruana/fc8ed4de/main/rules/Inside.list
ruleset=🌏 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
; 微软服务
ruleset=🧩 微软服务,https://raw.githubusercontent.com/utopeadia/myclashrule/main/rules/app/Microsoft.list
; 苹果服务
ruleset=🍏 苹果服务,https://raw.githubusercontent.com/utopeadia/myclashrule/main/rules/app/AppleOrIcloud.list
; 电报消息
ruleset=💬 电报消息,https://raw.githubusercontent.com/utopeadia/myclashrule/main/rules/app/telegram.list
; 社交媒体
ruleset=📲 社交媒体,https://raw.githubusercontent.com/AntonyCyrus/Rule/main/Clash/SocialMedia.list
; 大语言模型
ruleset=🤖 人工智能,https://raw.githubusercontent.com/utopeadia/myclashrule/main/rules/app/LLMProxy.list
; 学术研究
ruleset=📚 学术直连,https://raw.githubusercontent.com/utopeadia/myclashrule/main/rules/AcademicDirect.list
ruleset=📜 学术禁区,https://raw.githubusercontent.com/utopeadia/myclashrule/main/rules/AcademicProxy.list
; 开发环境/谷歌服务🔍
ruleset=👨‍ 开发服务,https://raw.githubusercontent.com/utopeadia/myclashrule/main/rules/MyProxy.list
ruleset=👨‍ 开发服务,https://raw.githubusercontent.com/Hruana/fc8ed4de/main/rules/Developer.list
ruleset=👨‍ 开发服务,https://raw.githubusercontent.com/utopeadia/myclashrule/main/rules/app/Google.list
; 香港流媒体
ruleset=📺 香港流媒体,https://raw.githubusercontent.com/AntonyCyrus/Rule/main/Clash/HKMedia.list
; 台湾流媒体
ruleset=📺 台湾流媒体,https://raw.githubusercontent.com/AntonyCyrus/Rule/main/Clash/TWMedia.list
; 日本流媒体
ruleset=📺 日本流媒体,https://raw.githubusercontent.com/AntonyCyrus/Rule/main/Clash/JPMedia.list
; 福利媒体
ruleset=🕊 福利媒体,https://raw.githubusercontent.com/EliceAM/Profiles/main/Clash/RuleSet/NSFW.list
ruleset=🕊 福利媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Porn.list
ruleset=🕊 福利媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PikPak/PikPak.list
ruleset=🕊 福利媒体,https://raw.githubusercontent.com/devswork/my-subconverter/master/rules/porn.list
; 常用流媒体
ruleset=🎥 常用流媒体,https://ruleset.skk.moe/Clash/non_ip/stream.txt
; 游戏合集
ruleset=🕹 游戏下载-CN,https://raw.githubusercontent.com/utopeadia/myclashrule/main/rules/app/GameDLCN.list
ruleset=🕹 游戏下载,https://raw.githubusercontent.com/utopeadia/myclashrule/main/rules/app/GameDL.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/utopeadia/myclashrule/main/rules/app/Game.list
; 工具合集🌐
ruleset=🛸 归属地伪装,https://raw.githubusercontent.com/lwd-temp/anti-ip-attribution/main/generated/rule-set-proxy.list
ruleset=📈 网络测试,https://raw.githubusercontent.com/DustinWin/ruleset_geodata/refs/heads/clash-ruleset/networktest.list
ruleset=💎 大流量下载,https://raw.githubusercontent.com/utopeadia/myclashrule/main/rules/Download.list
; 世界旅行
ruleset=🤠 世界旅行,https://raw.githubusercontent.com/Hruana/fc8ed4de/main/rules/Travel.list
; 禁区绕行
ruleset=🪜 禁区绕行,https://raw.githubusercontent.com/Hruana/fc8ed4de/main/rules/Outside.list
ruleset=🪜 禁区绕行,[]GEOSITE,proxy
; ruleset=🌏 全球直连,[]GEOSITE,cn
; ruleset=🌏 全球直连,[]GEOIP,LAN,no-resolve
; ruleset=🌏 全球直连,[]GEOIP,CN,no-resolve
ruleset=🐟 漏网之鱼,[]FINAL
;设置规则标志位

;设置分组标志位
custom_proxy_group=🪜 禁区绕行`select`[]♻ 自动选择`[]✈ 手动选择`[]🌏 全球直连`[]🇨🇳 自建节点`[]🇭🇰 香港自动`[]🇭🇰 香港手动`[]🇹🇼 台湾自动`[]🇹🇼 台湾手动`[]🇯🇵 日本自动`[]🇯🇵 日本手动`[]🇸🇬 狮城自动`[]🇸🇬 狮城手动`[]🇺🇸 美国自动`[]🇺🇸 美国手动`[]🇰🇷 韩国自动`[]🇰🇷 韩国手动`[]🗺️ 其他地区`[]🎥 流媒体节点`[]🧚 GPT解锁`[]🔯 故障转移`[]🔮 负载均衡
custom_proxy_group=✈ 手动选择`select`.*
;custom_proxy_group=♻ 自动选择`url-test`(^(?!.*(电信|联通|移动)).*)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=♻ 自动选择`url-test`.*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇨🇳 自建节点`select`(自建|hk-vmess|绿云|green)
custom_proxy_group=🇭🇰 香港自动`url-test`(香港|港|HK|Hong Kong|HongKong|🇭🇰)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇭🇰 香港手动`select`(香港|港|HK|Hong Kong|HongKong|🇭🇰)
custom_proxy_group=🇹🇼 台湾自动`url-test`(台湾|台|新北|彰化|TW|Taiwan|🇹🇼)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇹🇼 台湾手动`select`(台湾|台|新北|彰化|TW|Taiwan|🇹🇼)
custom_proxy_group=🇯🇵 日本自动`url-test`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan|🇯🇵)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇯🇵 日本手动`select`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan|🇯🇵)
custom_proxy_group=🇸🇬 狮城自动`url-test`(新加坡|坡|狮城|SG|Singapore|🇸🇬)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇸🇬 狮城手动`select`(新加坡|坡|狮城|SG|Singapore|🇸🇬)
custom_proxy_group=🇺🇸 美国自动`url-test`(UnitedStates|美国|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States|🇺🇸)`http://www.gstatic.com/generate_204`300,,150
custom_proxy_group=🇺🇸 美国手动`select`(UnitedStates|美国|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States|🇺🇸)
custom_proxy_group=🇰🇷 韩国自动`url-test`(韩国|KR|Korea|KOR|首尔|韩|韓|🇰🇷)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇰🇷 韩国手动`select`(韩国|KR|Korea|KOR|首尔|韩|韓|🇰🇷)
custom_proxy_group=🗺️ 其他地区`select`(^(?!.*(美|US|日|JP|港|HK|台|TW|新|SG|自建|hk-vmess|绿云|green|香港|港|HK|Hong Kong|HongKong|🇭🇰|台湾|台|新北|彰化|TW|Taiwan|🇹🇼|日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan|🇯🇵|新加坡|坡|狮城|SG|Singapore|🇸🇬|UnitedStates|美国|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States|🇺🇸|韩国|KR|Korea|KOR|首尔|韩|韓|🇰🇷|NF|奈飞|解锁|Netflix|NETFLIX|Media|gpt|GPT|chat|openai)).*)
custom_proxy_group=🎥 流媒体节点`select`(NF|原生|奈飞|解锁|流媒|迪士尼|N.*D|Netflix|NETFLIX|Media|Disn|Unlock|网易|音乐|解锁|Music|NetEase)
custom_proxy_group=🧚 GPT解锁`select`(gpt|GPT|chat|openai|ai)
custom_proxy_group=🔯 故障转移`fallback`.*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🔮 负载均衡`load-balance`.*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🌏 全球直连`select`[]DIRECT`[]✈ 手动选择`[]🇨🇳 自建节点
custom_proxy_group=🧩 微软服务`select`[]🌏 全球直连`[]🪜 禁区绕行`[]✈ 手动选择`[]🇨🇳 自建节点`[]🇭🇰 香港自动`[]🇹🇼 台湾自动`[]🇯🇵 日本自动`[]🇸🇬 狮城自动`[]🇺🇸 美国自动`[]🇰🇷 韩国自动`[]🗺️ 其他地区
custom_proxy_group=🍏 苹果服务`select`[]🌏 全球直连`[]🪜 禁区绕行`[]✈ 手动选择`[]🇨🇳 自建节点`[]🇭🇰 香港自动`[]🇹🇼 台湾自动`[]🇯🇵 日本自动`[]🇸🇬 狮城自动`[]🇺🇸 美国自动`[]🇰🇷 韩国自动`[]🗺️ 其他地区
custom_proxy_group=💬 电报消息`select`[]🪜 禁区绕行`[]🌏 全球直连`[]✈ 手动选择`[]🇨🇳 自建节点`[]🇭🇰 香港自动`[]🇭🇰 香港手动`[]🇹🇼 台湾自动`[]🇹🇼 台湾手动`[]🇯🇵 日本自动`[]🇯🇵 日本手动`[]🇸🇬 狮城自动`[]🇸🇬 狮城手动`[]🇺🇸 美国自动`[]🇺🇸 美国手动`[]🇰🇷 韩国自动`[]🇰🇷 韩国手动`[]🗺️ 其他地区
custom_proxy_group=📲 社交媒体`select`[]🪜 禁区绕行`[]🌏 全球直连`[]✈ 手动选择`[]🇨🇳 自建节点`[]🇭🇰 香港自动`[]🇭🇰 香港手动`[]🇹🇼 台湾自动`[]🇹🇼 台湾手动`[]🇯🇵 日本自动`[]🇯🇵 日本手动`[]🇸🇬 狮城自动`[]🇸🇬 狮城手动`[]🇺🇸 美国自动`[]🇺🇸 美国手动`[]🇰🇷 韩国自动`[]🇰🇷 韩国手动`[]🗺️ 其他地区
custom_proxy_group=🤖 人工智能`select`[]🧚 GPT解锁`[]🪜 禁区绕行`[]🌏 全球直连`[]✈ 手动选择`[]🇨🇳 自建节点`[]🇭🇰 香港手动`[]🇹🇼 台湾手动`[]🇯🇵 日本手动`[]🇸🇬 狮城手动`[]🇺🇸 美国手动`[]🇰🇷 韩国手动`[]🗺️ 其他地区
custom_proxy_group=📚 学术直连`select`[]🌏 全球直连`[]🪜 禁区绕行`[]✈ 手动选择`[]🇨🇳 自建节点
custom_proxy_group=📜 学术禁区`select`[]🪜 禁区绕行`[]🌏 全球直连`[]✈ 手动选择`[]🇨🇳 自建节点`[]🇭🇰 香港自动`[]🇭🇰 香港手动`[]🇹🇼 台湾自动`[]🇹🇼 台湾手动`[]🇯🇵 日本自动`[]🇯🇵 日本手动`[]🇸🇬 狮城自动`[]🇸🇬 狮城手动`[]🇺🇸 美国自动`[]🇺🇸 美国手动`[]🇰🇷 韩国自动`[]🇰🇷 韩国手动`[]🗺️ 其他地区
custom_proxy_group=👨‍ 开发服务`select`[]🪜 禁区绕行`[]🌏 全球直连`[]✈ 手动选择`[]🇨🇳 自建节点`[]🇭🇰 香港自动`[]🇭🇰 香港手动`[]🇹🇼 台湾自动`[]🇹🇼 台湾手动`[]🇯🇵 日本自动`[]🇯🇵 日本手动`[]🇸🇬 狮城自动`[]🇸🇬 狮城手动`[]🇺🇸 美国自动`[]🇺🇸 美国手动`[]🇰🇷 韩国自动`[]🇰🇷 韩国手动`[]🗺️ 其他地区
custom_proxy_group=🎥 常用流媒体`select`[]🎥 流媒体节点`[]🪜 禁区绕行`[]🌏 全球直连`[]✈ 手动选择`[]🇨🇳 自建节点`[]🇭🇰 香港自动`[]🇹🇼 台湾自动`[]🇯🇵 日本自动`[]🇸🇬 狮城自动`[]🇺🇸 美国自动`[]🇰🇷 韩国自动`[]🗺️ 其他地区
custom_proxy_group=📺 香港流媒体`select`[]🇭🇰 香港自动`[]🇭🇰 香港手动`[]🪜 禁区绕行`[]🌏 全球直连
custom_proxy_group=📺 台湾流媒体`select`[]🇹🇼 台湾自动`[]🇹🇼 台湾手动`[]🪜 禁区绕行`[]🌏 全球直连
custom_proxy_group=📺 日本流媒体`select`[]🇯🇵 日本自动`[]🇯🇵 日本手动`[]🪜 禁区绕行`[]🌏 全球直连
custom_proxy_group=🕊 福利媒体`select`[]🪜 禁区绕行`[]🌏 全球直连`[]✈ 手动选择`[]🇨🇳 自建节点`[]🇭🇰 香港自动`[]🇹🇼 台湾自动`[]🇯🇵 日本自动`[]🇸🇬 狮城自动`[]🇺🇸 美国自动`[]🇰🇷 韩国自动`[]🗺️ 其他地区
custom_proxy_group=🕹 游戏下载-CN`select`[]🌏 全球直连`[]🪜 禁区绕行`[]✈ 手动选择`[]🇨🇳 自建节点`[]🇭🇰 香港自动`[]🇭🇰 香港手动`[]🇹🇼 台湾自动`[]🇹🇼 台湾手动`[]🇯🇵 日本自动`[]🇯🇵 日本手动`[]🇸🇬 狮城自动`[]🇸🇬 狮城手动`[]🇺🇸 美国自动`[]🇺🇸 美国手动`[]🇰🇷 韩国自动`[]🇰🇷 韩国手动`[]🗺️ 其他地区
custom_proxy_group=🕹 游戏下载`select`[]🌏 全球直连`[]🪜 禁区绕行`[]✈ 手动选择`[]🇨🇳 自建节点`[]🇭🇰 香港自动`[]🇭🇰 香港手动`[]🇹🇼 台湾自动`[]🇹🇼 台湾手动`[]🇯🇵 日本自动`[]🇯🇵 日本手动`[]🇸🇬 狮城自动`[]🇸🇬 狮城手动`[]🇺🇸 美国自动`[]🇺🇸 美国手动`[]🇰🇷 韩国自动`[]🇰🇷 韩国手动`[]🗺️ 其他地区
custom_proxy_group=🎮 游戏平台`select`[]🌏 全球直连`[]🪜 禁区绕行`[]✈ 手动选择`[]🇨🇳 自建节点`[]🇭🇰 香港自动`[]🇭🇰 香港手动`[]🇹🇼 台湾自动`[]🇹🇼 台湾手动`[]🇯🇵 日本自动`[]🇯🇵 日本手动`[]🇸🇬 狮城自动`[]🇸🇬 狮城手动`[]🇺🇸 美国自动`[]🇺🇸 美国手动`[]🇰🇷 韩国自动`[]🇰🇷 韩国手动`[]🗺️ 其他地区
custom_proxy_group=🛸 归属地伪装`select`[]🌏 全球直连`(CN|电信|联通|移动)`[]🪜 禁区绕行`[]✈ 手动选择`[]🇨🇳 自建节点
custom_proxy_group=📈 网络测试`select`[]🌏 全球直连`[]🪜 禁区绕行`[]✈ 手动选择`[]🇨🇳 自建节点`[]🇭🇰 香港自动`[]🇭🇰 香港手动`[]🇹🇼 台湾自动`[]🇹🇼 台湾手动`[]🇯🇵 日本自动`[]🇯🇵 日本手动`[]🇸🇬 狮城自动`[]🇸🇬 狮城手动`[]🇺🇸 美国自动`[]🇺🇸 美国手动`[]🇰🇷 韩国自动`[]🇰🇷 韩国手动`[]🗺️ 其他地区
custom_proxy_group=💎 大流量下载`select`[]🌏 全球直连`[]🪜 禁区绕行`[]✈ 手动选择`[]🇨🇳 自建节点`[]🇭🇰 香港自动`[]🇭🇰 香港手动`[]🇹🇼 台湾自动`[]🇹🇼 台湾手动`[]🇯🇵 日本自动`[]🇯🇵 日本手动`[]🇸🇬 狮城自动`[]🇸🇬 狮城手动`[]🇺🇸 美国自动`[]🇺🇸 美国手动`[]🇰🇷 韩国自动`[]🇰🇷 韩国手动`[]🗺️ 其他地区
custom_proxy_group=🤠 世界旅行`select`[]🌏 全球直连`[]✈ 手动选择`[]🇨🇳 自建节点`[]🇭🇰 香港手动`[]🇹🇼 台湾手动`[]🇯🇵 日本手动`[]🇸🇬 狮城手动`[]🇺🇸 美国手动`[]🇰🇷 韩国手动`[]🗺️ 其他地区
custom_proxy_group=🐟 漏网之鱼`select`[]🪜 禁区绕行`[]🌏 全球直连`[]✈ 手动选择`[]🇨🇳 自建节点`[]🇭🇰 香港自动`[]🇭🇰 香港手动`[]🇹🇼 台湾自动`[]🇹🇼 台湾手动`[]🇯🇵 日本自动`[]🇯🇵 日本手动`[]🇸🇬 狮城自动`[]🇸🇬 狮城手动`[]🇺🇸 美国自动`[]🇺🇸 美国手动`[]🇰🇷 韩国自动`[]🇰🇷 韩国手动`[]🗺️ 其他地区
;设置分组标志位

;clash_rule_base=https://raw.githubusercontent.com/utopeadia/myclashrule/main/base/ClashBaseRule.yml
clash_rule_base=https://raw.githubusercontent.com/utopeadia/myclashrule/main/base/ClashBaseRuleNoDNSLeaks.yml
;singbox_rule_base=https://raw.githubusercontent.com/utopeadia/myclashrule/main/base/SingboxBaseRule.json
enable_rule_generator=true
overwrite_original_rules=true
;luck
